In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from matplotlib import pyplot as plt
import re
from IPython.display import Image

plt.style.use('fivethirtyeight')

In [ ]:
DATA_URL = 'https://ids-storage-football-prediction.s3-eu-west-1.amazonaws.com/data_mmwd/listings_polarity_distance.csv'
SCALED_DATA_URL = 'https://ids-storage-football-prediction.s3-eu-west-1.amazonaws.com/data_mmwd/listings_scalled.csv'

In [ ]:
df = pd.read_csv(SCALED_DATA_URL, index_col='Unnamed: 0')

In [ ]:
df.head()

       id  ... scaled_polarity
0   36642  ...        0.892230
1   59258  ...        0.992090
2  158824  ...        0.856325
3  261065  ...        0.905358
4  336692  ...        0.974530

[5 rows x 17 columns]

In [ ]:
BEDROOMS = 3
BEDS = -1
ACCOMMODATES = -1
BATHROOMS = 1
MAX_PRICE = 300

In [ ]:
filters = {
    'bedrooms': BEDROOMS,
    'beds': BEDS,
    'accommodates': ACCOMMODATES,
    'bathrooms': BATHROOMS
}

sub_filters = {
    'bedrooms': BEDROOMS + 1,
    'beds': BEDS + 1,
    'accommodates': ACCOMMODATES + 1,
    'bathrooms': BATHROOMS + 1
}

sub_sub_filters = {
    'bedrooms': BEDROOMS - 1,
    'beds': BEDS - 1,
    'accommodates': ACCOMMODATES - 1,
    'bathrooms': BATHROOMS - 1
}

In [ ]:
features_to_filter = []
features_no_filter = []

if BEDROOMS != -1:
  features_to_filter.append('bedrooms')
else:
  features_no_filter.append('bedrooms')

if BEDS != -1:
  features_to_filter.append('beds')
else:
  features_no_filter.append('beds')

if ACCOMMODATES != -1:
  features_to_filter.append('accommodates')
else:
  features_no_filter.append('accommodates')

if BATHROOMS != -1:
  features_to_filter.append('bathrooms')
else:
  features_no_filter.append('bathrooms')

In [ ]:
filtered_df = df

for feature in features_to_filter:
  if feature == 'bathrooms' or feature == 'beds':
    filtered_df = filtered_df[(filtered_df[feature] == filters[feature]) | (filtered_df[feature] == sub_filters[feature]) | (filtered_df[feature] == sub_sub_filters[feature])]
  else:
    filtered_df = filtered_df[(filtered_df[feature] == filters[feature]) | (filtered_df[feature] == sub_filters[feature])]

In [ ]:
filtered_df = filtered_df[filtered_df['price'] <= MAX_PRICE]

In [ ]:
filtered_df.shape

(216, 17)

In [ ]:
filtered_df.head()

         id  ... scaled_polarity
8    674799  ...        0.989958
14   793593  ...        0.984348
36  1774018  ...        0.856325
38  1827668  ...        0.864123
49  2631572  ...        0.924151

[5 rows x 17 columns]

In [ ]:
filtered_df['classified'] = 3 * filtered_df['scaled_polarity'] + 2 * filtered_df['scaled_distance'] + 1 * filtered_df['scaled_number_of_reviews']

In [ ]:
filtered_df.sort_values(by=['classified'], ascending=False)

            id  ... classified
697   20932401  ...   4.002767
638   19573750  ...   3.987546
108    6197420  ...   3.896060
1798  42120338  ...   3.740085
489   18433047  ...   3.695330
...        ...  ...        ...
847   23695729  ...   1.985670
1877  43970806  ...   1.952168
1900  44447250  ...   1.900550
891   24798562  ...   1.780083
1896  44359755  ...   1.637282

[216 rows x 18 columns]